CREATE TABLE
    IF NOT EXISTS `eDesempenoCPA` (
        `id` INT NOT NULL AUTO_INCREMENT,
        `id_evaluador` INTEGER NOT NULL,
        `id_evaluado` INTEGER NOT NULL,
        `fecha` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        `campaña` VARCHAR(250) NOT NULL,
        `cargo` VARCHAR(250) NOT NULL,
        `promedio_1` DECIMAL(3, 1) NOT NULL,
        `promedio_2` DECIMAL(3, 1) NOT NULL,
        `promedio_3` DECIMAL(3, 1) NOT NULL,
        `promedio_4` DECIMAL(3, 1) NOT NULL,
        `promedio_5` DECIMAL(3, 1) NOT NULL,
        `promedio_6` DECIMAL(3, 1) NOT NULL,
        `promedio_7` DECIMAL(3, 1) NOT NULL,
        `promedioCriterios` DECIMAL(3, 1) NOT NULL,
        `objetivo_1` TEXT NOT NULL,
        `meta_1` INTEGER NOT NULL,
        `rObjetivo_1` INTEGER NOT NULL,
        `ponderacionObjetivo_1` VARCHAR(50) NOT NULL,
        `objetivo_2` TEXT NOT NULL,
        `meta_2` INTEGER NOT NULL,
        `rObjetivo_2` INTEGER,
        `ponderacionObjetivo_2` VARCHAR(50),
        `objetivo_3` TEXT,
        `meta_3` INTEGER,
        `rObjetivo_3` INTEGER,
        `ponderacionObjetivo_3` VARCHAR(50),
        `objetivo_4` TEXT,
        `meta_4` INTEGER,
        `rObjetivo_4` INTEGER,
        `ponderacionObjetivo_4` VARCHAR(50),
        `objetivo_5` TEXT,
        `meta_5` INTEGER,
        `rObjetivo_5` INTEGER,
        `ponderacionObjetivo_5` VARCHAR(50),
        `objetivo_6` TEXT,
        `meta_6` INTEGER,
        `rObjetivo_6` INTEGER,
        `ponderacionObjetivo_6` VARCHAR(50),
        `objetivo_7` TEXT,
        `meta_7` INTEGER,
        `rObjetivo_7` INTEGER,
        `ponderacionObjetivo_7` VARCHAR(50),
        `objetivo_8` TEXT,
        `meta_8` INTEGER,
        `rObjetivo_8` INTEGER,
        `ponderacionObjetivo_8` VARCHAR(50),
        `objetivo_9` TEXT,
        `meta_9` INTEGER,
        `rObjetivo_9` INTEGER,
        `ponderacionObjetivo_9` VARCHAR(50),
        `objetivo_10` TEXT,
        `meta_10` INTEGER,
        `rObjetivo_10` INTEGER,
        `ponderacionObjetivo_10` VARCHAR(50),
        `compromisos` TEXT NOT NULL,
        `desarrolloP` TEXT NOT NULL,
        `obsEvaluador` TEXT NOT NULL,
        `obsEvaluado` TEXT NOT NULL,
        `promedioObjetivos` DECIMAL(3, 1) NOT NULL,
        `pFinal` DECIMAL(3, 1) NOT NULL,
        PRIMARY KEY `pk_id`(`id`)
    )